# Generated by Django 4.2.6 on 2023-10-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
