# Generated by Django 4.2.6 on 2023-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_blocked_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Faqs',
                'verbose_name_plural': 'Faqs',
                'db_table': 'faqs',
                'managed': True,
            },
        ),
    ]
